services:
  app:
    build: .
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/telegramUsers
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: postpass

  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: telegramUsers
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postpass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: